apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: deadletter-sub
spec:
  pubsubname: demo7-pubsub
  topic: deadletter-messages
  routes:
    default: /messagehandler
scopes:
- deadletter
