### Routing
@senderUrl=http://localhost:5233
### Send Type 1
POST {{senderUrl}}/send
Content-Type: application/json

{
  "id": "{{ $guid }}",
  "timeStamp": "{{ $datetime iso8601 }}",
  "type": "dapr.demo.type1"
}


### Send Type 2
POST {{senderUrl}}/send
Content-Type: application/json

{
  "id": "{{ $guid }}",
  "timeStamp": "{{ $datetime iso8601 }}",
  "type": "dapr.demo.type2"
}

### Send Type 1 with amount > 10
POST {{senderUrl}}/send
Content-Type: application/json

{
  "id": "{{ $guid }}",
  "timeStamp": "{{ $datetime iso8601 }}",
  "amount": 100,
  "type": "dapr.demo.type1"
}