apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: receiver-sub
spec:
  pubsubname: demo6-pubsub
  topic: incoming-messages
  routes:
    rules:
      - match: event.data.type == "dapr.demo.type2"
        path: /handletype2
    # If receiver2 should only receive type2 message do not use a default route.
    # default: /messagehandler
scopes:
- receiver2
